//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Shift.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("E_Shift.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6414dcfeccd18910916cdaa4_thumbnail_5_blog_movers_webflow_template {
            get {
                object obj = ResourceManager.GetObject("6414dcfeccd18910916cdaa4_thumbnail-5-blog-movers-webflow-template", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6414dcfeccd1891fd16cd9fd_follow_our_work_on_instagram_photo_five_movers_x_webflow_template {
            get {
                object obj = ResourceManager.GetObject("6414dcfeccd1891fd16cd9fd_follow-our-work-on-instagram-photo-five-movers-x-webflow" +
                        "-template", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6414dcfeccd18934ae6cda46_the_story_behind_our_company_first_article_movers_x_webflow_template_p_800 {
            get {
                object obj = ResourceManager.GetObject("6414dcfeccd18934ae6cda46_the-story-behind-our-company-first-article-movers-x-webf" +
                        "low-template-p-800", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6414dcfeccd189382e6cda45_the_story_behind_our_company_second_article_movers_x_webflow_template_p_800 {
            get {
                object obj = ResourceManager.GetObject("6414dcfeccd189382e6cda45_the-story-behind-our-company-second-article-movers-x-web" +
                        "flow-template-p-800", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6414dcfeccd1893b5f6cda43_about_our_company_first_movers_x_webflow_template_p_1080 {
            get {
                object obj = ResourceManager.GetObject("6414dcfeccd1893b5f6cda43_about-our-company-first-movers-x-webflow-template-p-1080" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6414dcfeccd18942666cd9cb_we_make_moving_fast_and_easy_movers_x_webflow_template_p_800 {
            get {
                object obj = ResourceManager.GetObject("6414dcfeccd18942666cd9cb_we-make-moving-fast-and-easy-movers-x-webflow-template-p" +
                        "-800", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6414dcfeccd1894a9c6cda44_about_our_company_second_movers_x_webflow_template_p_1080 {
            get {
                object obj = ResourceManager.GetObject("6414dcfeccd1894a9c6cda44_about-our-company-second-movers-x-webflow-template-p-108" +
                        "0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6414dcfeccd1897d436cdaa1_thumbnail_4_blog_movers_webflow_template {
            get {
                object obj = ResourceManager.GetObject("6414dcfeccd1897d436cdaa1_thumbnail-4-blog-movers-webflow-template", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6414dcfeccd18985316cda88_thumbnail_2_blog_movers_webflow_template {
            get {
                object obj = ResourceManager.GetObject("6414dcfeccd18985316cda88_thumbnail-2-blog-movers-webflow-template", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6414dcfeccd18986816cd9fc_follow_our_work_on_instagram_photo_three_movers_x_webflow_template {
            get {
                object obj = ResourceManager.GetObject("6414dcfeccd18986816cd9fc_follow-our-work-on-instagram-photo-three-movers-x-webflo" +
                        "w-template", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6414dcfeccd1898bf16cd9fb_follow_our_work_on_instagram_photo_one_movers_x_webflow_template {
            get {
                object obj = ResourceManager.GetObject("6414dcfeccd1898bf16cd9fb_follow-our-work-on-instagram-photo-one-movers-x-webflow-" +
                        "template", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6414dcfeccd1898cd46cd9fe_follow_our_work_on_instagram_photo_two_movers_x_webflow_template {
            get {
                object obj = ResourceManager.GetObject("6414dcfeccd1898cd46cd9fe_follow-our-work-on-instagram-photo-two-movers-x-webflow-" +
                        "template", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6414dcfeccd189a54f6cd9fa_follow_our_work_on_instagram_photo_four_movers_x_webflow_template {
            get {
                object obj = ResourceManager.GetObject("6414dcfeccd189a54f6cd9fa_follow-our-work-on-instagram-photo-four-movers-x-webflow" +
                        "-template", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6414dcfeccd189c4ed6cda85_thumbnail_1_blog_movers_webflow_template {
            get {
                object obj = ResourceManager.GetObject("6414dcfeccd189c4ed6cda85_thumbnail-1-blog-movers-webflow-template", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6414dcfeccd189c8536cdaa8_thumbnail_featured_6_blog_movers_webflow_template {
            get {
                object obj = ResourceManager.GetObject("6414dcfeccd189c8536cdaa8_thumbnail-featured-6-blog-movers-webflow-template", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6414dcfeccd189dcb16cda8c_thumbnail_3_blog_movers_webflow_template {
            get {
                object obj = ResourceManager.GetObject("6414dcfeccd189dcb16cda8c_thumbnail-3-blog-movers-webflow-template", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Delivery_Express_Logo__3_ {
            get {
                object obj = ResourceManager.GetObject("Delivery Express Logo (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2025_07_03_022514 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2025-07-03 022514", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2025_07_03_0225141 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2025-07-03 0225141", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2025_07_03_022830 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2025-07-03 022830", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2025_07_03_0228301 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2025-07-03 0228301", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2025_07_03_022852 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2025-07-03 022852", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2025_07_03_0228521 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2025-07-03 0228521", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2025_07_03_0228522 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2025-07-03 0228522", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2025_07_03_022903 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2025-07-03 022903", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2025_07_03_0229031 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2025-07-03 0229031", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2025_07_03_024210 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2025-07-03 024210", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2025_07_31_160902 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2025-07-31 160902", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2025_07_31_161823 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2025-07-31 161823", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
